name: Main

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: "Build"
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest]

    steps:
    - uses: actions/checkout@v4
    - uses: actions/cache@v4
      id: cache-deps
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - name: Build
      run: cargo build --release --verbose
    - name: Run clippy
      run: cargo clippy
    - name: Run tests
      run: cargo test --verbose
    - name: Prepare Artifacts
      if: runner.os == 'Windows'
      run: |
        mv target/release/* .
        mv scripts/run_artifacts_windows.bat run.bat
    - name: Prepare Artifacts
      if: runner.os == 'Linux'
      run: |
        mv target/release/* .
        mv scripts/run_artifacts_linux.sh run.sh
    - name: Archive artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Kodama-${{ runner.os }}
        path: |
          LICENSE
          USAGE.md
          README.md
          Caddyfile
          kodama-lobby*
          kodama-login*
          kodama-patch*
          kodama-web*
          kodama-world*
          !*.d
          resources/
          !resources/tests
          !resources/opcodes.json
          run.sh
          run.bat
